// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.31.1
// source: proto/fiscal.proto

package fiscal

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	FiscalService_EmitirNotaFiscal_FullMethodName = "/fiscal.FiscalService/EmitirNotaFiscal"
)

// FiscalServiceClient is the client API for FiscalService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FiscalServiceClient interface {
	EmitirNotaFiscal(ctx context.Context, in *EmitirNotaFiscalRequest, opts ...grpc.CallOption) (*EmitirNotaFiscalResponse, error)
}

type fiscalServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewFiscalServiceClient(cc grpc.ClientConnInterface) FiscalServiceClient {
	return &fiscalServiceClient{cc}
}

func (c *fiscalServiceClient) EmitirNotaFiscal(ctx context.Context, in *EmitirNotaFiscalRequest, opts ...grpc.CallOption) (*EmitirNotaFiscalResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EmitirNotaFiscalResponse)
	err := c.cc.Invoke(ctx, FiscalService_EmitirNotaFiscal_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FiscalServiceServer is the server API for FiscalService service.
// All implementations must embed UnimplementedFiscalServiceServer
// for forward compatibility.
type FiscalServiceServer interface {
	EmitirNotaFiscal(context.Context, *EmitirNotaFiscalRequest) (*EmitirNotaFiscalResponse, error)
	mustEmbedUnimplementedFiscalServiceServer()
}

// UnimplementedFiscalServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFiscalServiceServer struct{}

func (UnimplementedFiscalServiceServer) EmitirNotaFiscal(context.Context, *EmitirNotaFiscalRequest) (*EmitirNotaFiscalResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EmitirNotaFiscal not implemented")
}
func (UnimplementedFiscalServiceServer) mustEmbedUnimplementedFiscalServiceServer() {}
func (UnimplementedFiscalServiceServer) testEmbeddedByValue()                       {}

// UnsafeFiscalServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FiscalServiceServer will
// result in compilation errors.
type UnsafeFiscalServiceServer interface {
	mustEmbedUnimplementedFiscalServiceServer()
}

func RegisterFiscalServiceServer(s grpc.ServiceRegistrar, srv FiscalServiceServer) {
	// If the following call pancis, it indicates UnimplementedFiscalServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&FiscalService_ServiceDesc, srv)
}

func _FiscalService_EmitirNotaFiscal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmitirNotaFiscalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FiscalServiceServer).EmitirNotaFiscal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FiscalService_EmitirNotaFiscal_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FiscalServiceServer).EmitirNotaFiscal(ctx, req.(*EmitirNotaFiscalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// FiscalService_ServiceDesc is the grpc.ServiceDesc for FiscalService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FiscalService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "fiscal.FiscalService",
	HandlerType: (*FiscalServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "EmitirNotaFiscal",
			Handler:    _FiscalService_EmitirNotaFiscal_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/fiscal.proto",
}
