global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'api-catalogo'
    static_configs:
      - targets: ['host.docker.internal:2112']

  - job_name: 'api-estoque'
    static_configs:
      - targets: ['host.docker.internal:2113']

  - job_name: 'api-fiscal'
    static_configs:
      - targets: ['host.docker.internal:2114']

  - job_name: 'api-logistica'
    static_configs:
      - targets: ['host.docker.internal:2115']

  - job_name: 'api-pagamentos'
    static_configs:
      - targets: ['host.docker.internal:2116']

  - job_name: 'api-pedidos'
    static_configs:
      - targets: ['host.docker.internal:2117']
