// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: proto/catalogo.proto

package catalogo

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ListarProdutosRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListarProdutosRequest) Reset() {
	*x = ListarProdutosRequest{}
	mi := &file_proto_catalogo_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListarProdutosRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListarProdutosRequest) ProtoMessage() {}

func (x *ListarProdutosRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_catalogo_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListarProdutosRequest.ProtoReflect.Descriptor instead.
func (*ListarProdutosRequest) Descriptor() ([]byte, []int) {
	return file_proto_catalogo_proto_rawDescGZIP(), []int{0}
}

type Produto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Nome          string                 `protobuf:"bytes,2,opt,name=nome,proto3" json:"nome,omitempty"`
	Estoque       int32                  `protobuf:"varint,3,opt,name=estoque,proto3" json:"estoque,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Produto) Reset() {
	*x = Produto{}
	mi := &file_proto_catalogo_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Produto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Produto) ProtoMessage() {}

func (x *Produto) ProtoReflect() protoreflect.Message {
	mi := &file_proto_catalogo_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Produto.ProtoReflect.Descriptor instead.
func (*Produto) Descriptor() ([]byte, []int) {
	return file_proto_catalogo_proto_rawDescGZIP(), []int{1}
}

func (x *Produto) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Produto) GetNome() string {
	if x != nil {
		return x.Nome
	}
	return ""
}

func (x *Produto) GetEstoque() int32 {
	if x != nil {
		return x.Estoque
	}
	return 0
}

type ListarProdutosResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Produtos      []*Produto             `protobuf:"bytes,1,rep,name=produtos,proto3" json:"produtos,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListarProdutosResponse) Reset() {
	*x = ListarProdutosResponse{}
	mi := &file_proto_catalogo_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListarProdutosResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListarProdutosResponse) ProtoMessage() {}

func (x *ListarProdutosResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_catalogo_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListarProdutosResponse.ProtoReflect.Descriptor instead.
func (*ListarProdutosResponse) Descriptor() ([]byte, []int) {
	return file_proto_catalogo_proto_rawDescGZIP(), []int{2}
}

func (x *ListarProdutosResponse) GetProdutos() []*Produto {
	if x != nil {
		return x.Produtos
	}
	return nil
}

var File_proto_catalogo_proto protoreflect.FileDescriptor

const file_proto_catalogo_proto_rawDesc = "" +
	"\n" +
	"\x14proto/catalogo.proto\x12\bcatalogo\"\x17\n" +
	"\x15ListarProdutosRequest\"G\n" +
	"\aProduto\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04nome\x18\x02 \x01(\tR\x04nome\x12\x18\n" +
	"\aestoque\x18\x03 \x01(\x05R\aestoque\"G\n" +
	"\x16ListarProdutosResponse\x12-\n" +
	"\bprodutos\x18\x01 \x03(\v2\x11.catalogo.ProdutoR\bprodutos2f\n" +
	"\x0fCatalogoService\x12S\n" +
	"\x0eListarProdutos\x12\x1f.catalogo.ListarProdutosRequest\x1a .catalogo.ListarProdutosResponseB\x1fZ\x1decommerce-grpc/proto/catalogob\x06proto3"

var (
	file_proto_catalogo_proto_rawDescOnce sync.Once
	file_proto_catalogo_proto_rawDescData []byte
)

func file_proto_catalogo_proto_rawDescGZIP() []byte {
	file_proto_catalogo_proto_rawDescOnce.Do(func() {
		file_proto_catalogo_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_catalogo_proto_rawDesc), len(file_proto_catalogo_proto_rawDesc)))
	})
	return file_proto_catalogo_proto_rawDescData
}

var file_proto_catalogo_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_catalogo_proto_goTypes = []any{
	(*ListarProdutosRequest)(nil),  // 0: catalogo.ListarProdutosRequest
	(*Produto)(nil),                // 1: catalogo.Produto
	(*ListarProdutosResponse)(nil), // 2: catalogo.ListarProdutosResponse
}
var file_proto_catalogo_proto_depIdxs = []int32{
	1, // 0: catalogo.ListarProdutosResponse.produtos:type_name -> catalogo.Produto
	0, // 1: catalogo.CatalogoService.ListarProdutos:input_type -> catalogo.ListarProdutosRequest
	2, // 2: catalogo.CatalogoService.ListarProdutos:output_type -> catalogo.ListarProdutosResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_catalogo_proto_init() }
func file_proto_catalogo_proto_init() {
	if File_proto_catalogo_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_catalogo_proto_rawDesc), len(file_proto_catalogo_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_catalogo_proto_goTypes,
		DependencyIndexes: file_proto_catalogo_proto_depIdxs,
		MessageInfos:      file_proto_catalogo_proto_msgTypes,
	}.Build()
	File_proto_catalogo_proto = out.File
	file_proto_catalogo_proto_goTypes = nil
	file_proto_catalogo_proto_depIdxs = nil
}
