// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.31.1
// source: proto/catalogo.proto

package catalogo

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CatalogoService_ListarProdutos_FullMethodName = "/catalogo.CatalogoService/ListarProdutos"
)

// CatalogoServiceClient is the client API for CatalogoService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CatalogoServiceClient interface {
	ListarProdutos(ctx context.Context, in *ListarProdutosRequest, opts ...grpc.CallOption) (*ListarProdutosResponse, error)
}

type catalogoServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCatalogoServiceClient(cc grpc.ClientConnInterface) CatalogoServiceClient {
	return &catalogoServiceClient{cc}
}

func (c *catalogoServiceClient) ListarProdutos(ctx context.Context, in *ListarProdutosRequest, opts ...grpc.CallOption) (*ListarProdutosResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListarProdutosResponse)
	err := c.cc.Invoke(ctx, CatalogoService_ListarProdutos_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CatalogoServiceServer is the server API for CatalogoService service.
// All implementations must embed UnimplementedCatalogoServiceServer
// for forward compatibility.
type CatalogoServiceServer interface {
	ListarProdutos(context.Context, *ListarProdutosRequest) (*ListarProdutosResponse, error)
	mustEmbedUnimplementedCatalogoServiceServer()
}

// UnimplementedCatalogoServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCatalogoServiceServer struct{}

func (UnimplementedCatalogoServiceServer) ListarProdutos(context.Context, *ListarProdutosRequest) (*ListarProdutosResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListarProdutos not implemented")
}
func (UnimplementedCatalogoServiceServer) mustEmbedUnimplementedCatalogoServiceServer() {}
func (UnimplementedCatalogoServiceServer) testEmbeddedByValue()                         {}

// UnsafeCatalogoServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CatalogoServiceServer will
// result in compilation errors.
type UnsafeCatalogoServiceServer interface {
	mustEmbedUnimplementedCatalogoServiceServer()
}

func RegisterCatalogoServiceServer(s grpc.ServiceRegistrar, srv CatalogoServiceServer) {
	// If the following call pancis, it indicates UnimplementedCatalogoServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CatalogoService_ServiceDesc, srv)
}

func _CatalogoService_ListarProdutos_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListarProdutosRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatalogoServiceServer).ListarProdutos(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CatalogoService_ListarProdutos_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatalogoServiceServer).ListarProdutos(ctx, req.(*ListarProdutosRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CatalogoService_ServiceDesc is the grpc.ServiceDesc for CatalogoService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CatalogoService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "catalogo.CatalogoService",
	HandlerType: (*CatalogoServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListarProdutos",
			Handler:    _CatalogoService_ListarProdutos_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/catalogo.proto",
}
