// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.31.1
// source: proto/logistica.proto

package logistica

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	LogisticaService_AgendarEnvio_FullMethodName = "/logistica.LogisticaService/AgendarEnvio"
)

// LogisticaServiceClient is the client API for LogisticaService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LogisticaServiceClient interface {
	AgendarEnvio(ctx context.Context, in *AgendarEnvioRequest, opts ...grpc.CallOption) (*AgendarEnvioResponse, error)
}

type logisticaServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewLogisticaServiceClient(cc grpc.ClientConnInterface) LogisticaServiceClient {
	return &logisticaServiceClient{cc}
}

func (c *logisticaServiceClient) AgendarEnvio(ctx context.Context, in *AgendarEnvioRequest, opts ...grpc.CallOption) (*AgendarEnvioResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AgendarEnvioResponse)
	err := c.cc.Invoke(ctx, LogisticaService_AgendarEnvio_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LogisticaServiceServer is the server API for LogisticaService service.
// All implementations must embed UnimplementedLogisticaServiceServer
// for forward compatibility.
type LogisticaServiceServer interface {
	AgendarEnvio(context.Context, *AgendarEnvioRequest) (*AgendarEnvioResponse, error)
	mustEmbedUnimplementedLogisticaServiceServer()
}

// UnimplementedLogisticaServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedLogisticaServiceServer struct{}

func (UnimplementedLogisticaServiceServer) AgendarEnvio(context.Context, *AgendarEnvioRequest) (*AgendarEnvioResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AgendarEnvio not implemented")
}
func (UnimplementedLogisticaServiceServer) mustEmbedUnimplementedLogisticaServiceServer() {}
func (UnimplementedLogisticaServiceServer) testEmbeddedByValue()                          {}

// UnsafeLogisticaServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LogisticaServiceServer will
// result in compilation errors.
type UnsafeLogisticaServiceServer interface {
	mustEmbedUnimplementedLogisticaServiceServer()
}

func RegisterLogisticaServiceServer(s grpc.ServiceRegistrar, srv LogisticaServiceServer) {
	// If the following call pancis, it indicates UnimplementedLogisticaServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&LogisticaService_ServiceDesc, srv)
}

func _LogisticaService_AgendarEnvio_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AgendarEnvioRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LogisticaServiceServer).AgendarEnvio(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LogisticaService_AgendarEnvio_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LogisticaServiceServer).AgendarEnvio(ctx, req.(*AgendarEnvioRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// LogisticaService_ServiceDesc is the grpc.ServiceDesc for LogisticaService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LogisticaService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "logistica.LogisticaService",
	HandlerType: (*LogisticaServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AgendarEnvio",
			Handler:    _LogisticaService_AgendarEnvio_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/logistica.proto",
}
