// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: proto/logistica.proto

package logistica

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AgendarEnvioRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PedidoId      int64                  `protobuf:"varint,1,opt,name=pedido_id,json=pedidoId,proto3" json:"pedido_id,omitempty"`
	NotaFiscalId  int64                  `protobuf:"varint,2,opt,name=nota_fiscal_id,json=notaFiscalId,proto3" json:"nota_fiscal_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgendarEnvioRequest) Reset() {
	*x = AgendarEnvioRequest{}
	mi := &file_proto_logistica_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgendarEnvioRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgendarEnvioRequest) ProtoMessage() {}

func (x *AgendarEnvioRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_logistica_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgendarEnvioRequest.ProtoReflect.Descriptor instead.
func (*AgendarEnvioRequest) Descriptor() ([]byte, []int) {
	return file_proto_logistica_proto_rawDescGZIP(), []int{0}
}

func (x *AgendarEnvioRequest) GetPedidoId() int64 {
	if x != nil {
		return x.PedidoId
	}
	return 0
}

func (x *AgendarEnvioRequest) GetNotaFiscalId() int64 {
	if x != nil {
		return x.NotaFiscalId
	}
	return 0
}

type AgendarEnvioResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Status             string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	CodigoRastreamento string                 `protobuf:"bytes,2,opt,name=codigo_rastreamento,json=codigoRastreamento,proto3" json:"codigo_rastreamento,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *AgendarEnvioResponse) Reset() {
	*x = AgendarEnvioResponse{}
	mi := &file_proto_logistica_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgendarEnvioResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgendarEnvioResponse) ProtoMessage() {}

func (x *AgendarEnvioResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_logistica_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgendarEnvioResponse.ProtoReflect.Descriptor instead.
func (*AgendarEnvioResponse) Descriptor() ([]byte, []int) {
	return file_proto_logistica_proto_rawDescGZIP(), []int{1}
}

func (x *AgendarEnvioResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *AgendarEnvioResponse) GetCodigoRastreamento() string {
	if x != nil {
		return x.CodigoRastreamento
	}
	return ""
}

var File_proto_logistica_proto protoreflect.FileDescriptor

const file_proto_logistica_proto_rawDesc = "" +
	"\n" +
	"\x15proto/logistica.proto\x12\tlogistica\"X\n" +
	"\x13AgendarEnvioRequest\x12\x1b\n" +
	"\tpedido_id\x18\x01 \x01(\x03R\bpedidoId\x12$\n" +
	"\x0enota_fiscal_id\x18\x02 \x01(\x03R\fnotaFiscalId\"_\n" +
	"\x14AgendarEnvioResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12/\n" +
	"\x13codigo_rastreamento\x18\x02 \x01(\tR\x12codigoRastreamento2c\n" +
	"\x10LogisticaService\x12O\n" +
	"\fAgendarEnvio\x12\x1e.logistica.AgendarEnvioRequest\x1a\x1f.logistica.AgendarEnvioResponseB Z\x1eecommerce-grpc/proto/logisticab\x06proto3"

var (
	file_proto_logistica_proto_rawDescOnce sync.Once
	file_proto_logistica_proto_rawDescData []byte
)

func file_proto_logistica_proto_rawDescGZIP() []byte {
	file_proto_logistica_proto_rawDescOnce.Do(func() {
		file_proto_logistica_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_logistica_proto_rawDesc), len(file_proto_logistica_proto_rawDesc)))
	})
	return file_proto_logistica_proto_rawDescData
}

var file_proto_logistica_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_logistica_proto_goTypes = []any{
	(*AgendarEnvioRequest)(nil),  // 0: logistica.AgendarEnvioRequest
	(*AgendarEnvioResponse)(nil), // 1: logistica.AgendarEnvioResponse
}
var file_proto_logistica_proto_depIdxs = []int32{
	0, // 0: logistica.LogisticaService.AgendarEnvio:input_type -> logistica.AgendarEnvioRequest
	1, // 1: logistica.LogisticaService.AgendarEnvio:output_type -> logistica.AgendarEnvioResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_logistica_proto_init() }
func file_proto_logistica_proto_init() {
	if File_proto_logistica_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_logistica_proto_rawDesc), len(file_proto_logistica_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_logistica_proto_goTypes,
		DependencyIndexes: file_proto_logistica_proto_depIdxs,
		MessageInfos:      file_proto_logistica_proto_msgTypes,
	}.Build()
	File_proto_logistica_proto = out.File
	file_proto_logistica_proto_goTypes = nil
	file_proto_logistica_proto_depIdxs = nil
}
