// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.31.1
// source: proto/pedidos.proto

package pedidos

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PedidosService_CriarPedido_FullMethodName = "/pedidos.PedidosService/CriarPedido"
)

// PedidosServiceClient is the client API for PedidosService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PedidosServiceClient interface {
	CriarPedido(ctx context.Context, in *CriarPedidoRequest, opts ...grpc.CallOption) (*CriarPedidoResponse, error)
}

type pedidosServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPedidosServiceClient(cc grpc.ClientConnInterface) PedidosServiceClient {
	return &pedidosServiceClient{cc}
}

func (c *pedidosServiceClient) CriarPedido(ctx context.Context, in *CriarPedidoRequest, opts ...grpc.CallOption) (*CriarPedidoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CriarPedidoResponse)
	err := c.cc.Invoke(ctx, PedidosService_CriarPedido_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PedidosServiceServer is the server API for PedidosService service.
// All implementations must embed UnimplementedPedidosServiceServer
// for forward compatibility.
type PedidosServiceServer interface {
	CriarPedido(context.Context, *CriarPedidoRequest) (*CriarPedidoResponse, error)
	mustEmbedUnimplementedPedidosServiceServer()
}

// UnimplementedPedidosServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPedidosServiceServer struct{}

func (UnimplementedPedidosServiceServer) CriarPedido(context.Context, *CriarPedidoRequest) (*CriarPedidoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CriarPedido not implemented")
}
func (UnimplementedPedidosServiceServer) mustEmbedUnimplementedPedidosServiceServer() {}
func (UnimplementedPedidosServiceServer) testEmbeddedByValue()                        {}

// UnsafePedidosServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PedidosServiceServer will
// result in compilation errors.
type UnsafePedidosServiceServer interface {
	mustEmbedUnimplementedPedidosServiceServer()
}

func RegisterPedidosServiceServer(s grpc.ServiceRegistrar, srv PedidosServiceServer) {
	// If the following call pancis, it indicates UnimplementedPedidosServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PedidosService_ServiceDesc, srv)
}

func _PedidosService_CriarPedido_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CriarPedidoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PedidosServiceServer).CriarPedido(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PedidosService_CriarPedido_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PedidosServiceServer).CriarPedido(ctx, req.(*CriarPedidoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PedidosService_ServiceDesc is the grpc.ServiceDesc for PedidosService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PedidosService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pedidos.PedidosService",
	HandlerType: (*PedidosServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CriarPedido",
			Handler:    _PedidosService_CriarPedido_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/pedidos.proto",
}
