global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'api-catalogo'
    static_configs:
      - targets: ['host.docker.internal:8086']

  - job_name: 'api-estoque'
    static_configs:
      - targets: ['host.docker.internal:8083']

  - job_name: 'api-fiscal'
    static_configs:
      - targets: ['host.docker.internal:8084']

  - job_name: 'api-logistica'
    static_configs:
      - targets: ['host.docker.internal:8085']

  - job_name: 'api-pagamentos'
    static_configs:
      - targets: ['host.docker.internal:8082']

  - job_name: 'api-pedidos'
    static_configs:
      - targets: ['host.docker.internal:8081']
