// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.31.1
// source: proto/estoque.proto

package estoque

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	EstoqueService_SepararEstoque_FullMethodName = "/estoque.EstoqueService/SepararEstoque"
)

// EstoqueServiceClient is the client API for EstoqueService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type EstoqueServiceClient interface {
	SepararEstoque(ctx context.Context, in *SepararEstoqueRequest, opts ...grpc.CallOption) (*SepararEstoqueResponse, error)
}

type estoqueServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewEstoqueServiceClient(cc grpc.ClientConnInterface) EstoqueServiceClient {
	return &estoqueServiceClient{cc}
}

func (c *estoqueServiceClient) SepararEstoque(ctx context.Context, in *SepararEstoqueRequest, opts ...grpc.CallOption) (*SepararEstoqueResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SepararEstoqueResponse)
	err := c.cc.Invoke(ctx, EstoqueService_SepararEstoque_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EstoqueServiceServer is the server API for EstoqueService service.
// All implementations must embed UnimplementedEstoqueServiceServer
// for forward compatibility.
type EstoqueServiceServer interface {
	SepararEstoque(context.Context, *SepararEstoqueRequest) (*SepararEstoqueResponse, error)
	mustEmbedUnimplementedEstoqueServiceServer()
}

// UnimplementedEstoqueServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedEstoqueServiceServer struct{}

func (UnimplementedEstoqueServiceServer) SepararEstoque(context.Context, *SepararEstoqueRequest) (*SepararEstoqueResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SepararEstoque not implemented")
}
func (UnimplementedEstoqueServiceServer) mustEmbedUnimplementedEstoqueServiceServer() {}
func (UnimplementedEstoqueServiceServer) testEmbeddedByValue()                        {}

// UnsafeEstoqueServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EstoqueServiceServer will
// result in compilation errors.
type UnsafeEstoqueServiceServer interface {
	mustEmbedUnimplementedEstoqueServiceServer()
}

func RegisterEstoqueServiceServer(s grpc.ServiceRegistrar, srv EstoqueServiceServer) {
	// If the following call pancis, it indicates UnimplementedEstoqueServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&EstoqueService_ServiceDesc, srv)
}

func _EstoqueService_SepararEstoque_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SepararEstoqueRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EstoqueServiceServer).SepararEstoque(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EstoqueService_SepararEstoque_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EstoqueServiceServer).SepararEstoque(ctx, req.(*SepararEstoqueRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// EstoqueService_ServiceDesc is the grpc.ServiceDesc for EstoqueService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EstoqueService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "estoque.EstoqueService",
	HandlerType: (*EstoqueServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SepararEstoque",
			Handler:    _EstoqueService_SepararEstoque_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/estoque.proto",
}
