// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: proto/estoque.proto

package estoque

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SepararEstoqueRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PedidoId      int64                  `protobuf:"varint,1,opt,name=pedido_id,json=pedidoId,proto3" json:"pedido_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SepararEstoqueRequest) Reset() {
	*x = SepararEstoqueRequest{}
	mi := &file_proto_estoque_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SepararEstoqueRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SepararEstoqueRequest) ProtoMessage() {}

func (x *SepararEstoqueRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_estoque_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SepararEstoqueRequest.ProtoReflect.Descriptor instead.
func (*SepararEstoqueRequest) Descriptor() ([]byte, []int) {
	return file_proto_estoque_proto_rawDescGZIP(), []int{0}
}

func (x *SepararEstoqueRequest) GetPedidoId() int64 {
	if x != nil {
		return x.PedidoId
	}
	return 0
}

type SepararEstoqueResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SepararEstoqueResponse) Reset() {
	*x = SepararEstoqueResponse{}
	mi := &file_proto_estoque_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SepararEstoqueResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SepararEstoqueResponse) ProtoMessage() {}

func (x *SepararEstoqueResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_estoque_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SepararEstoqueResponse.ProtoReflect.Descriptor instead.
func (*SepararEstoqueResponse) Descriptor() ([]byte, []int) {
	return file_proto_estoque_proto_rawDescGZIP(), []int{1}
}

func (x *SepararEstoqueResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_proto_estoque_proto protoreflect.FileDescriptor

const file_proto_estoque_proto_rawDesc = "" +
	"\n" +
	"\x13proto/estoque.proto\x12\aestoque\"4\n" +
	"\x15SepararEstoqueRequest\x12\x1b\n" +
	"\tpedido_id\x18\x01 \x01(\x03R\bpedidoId\"0\n" +
	"\x16SepararEstoqueResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status2c\n" +
	"\x0eEstoqueService\x12Q\n" +
	"\x0eSepararEstoque\x12\x1e.estoque.SepararEstoqueRequest\x1a\x1f.estoque.SepararEstoqueResponseB\x1eZ\x1cecommerce-grpc/proto/estoqueb\x06proto3"

var (
	file_proto_estoque_proto_rawDescOnce sync.Once
	file_proto_estoque_proto_rawDescData []byte
)

func file_proto_estoque_proto_rawDescGZIP() []byte {
	file_proto_estoque_proto_rawDescOnce.Do(func() {
		file_proto_estoque_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_estoque_proto_rawDesc), len(file_proto_estoque_proto_rawDesc)))
	})
	return file_proto_estoque_proto_rawDescData
}

var file_proto_estoque_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_estoque_proto_goTypes = []any{
	(*SepararEstoqueRequest)(nil),  // 0: estoque.SepararEstoqueRequest
	(*SepararEstoqueResponse)(nil), // 1: estoque.SepararEstoqueResponse
}
var file_proto_estoque_proto_depIdxs = []int32{
	0, // 0: estoque.EstoqueService.SepararEstoque:input_type -> estoque.SepararEstoqueRequest
	1, // 1: estoque.EstoqueService.SepararEstoque:output_type -> estoque.SepararEstoqueResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_estoque_proto_init() }
func file_proto_estoque_proto_init() {
	if File_proto_estoque_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_estoque_proto_rawDesc), len(file_proto_estoque_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_estoque_proto_goTypes,
		DependencyIndexes: file_proto_estoque_proto_depIdxs,
		MessageInfos:      file_proto_estoque_proto_msgTypes,
	}.Build()
	File_proto_estoque_proto = out.File
	file_proto_estoque_proto_goTypes = nil
	file_proto_estoque_proto_depIdxs = nil
}
