// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: proto/pagamentos.proto

package pagamentos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ProcessarPagamentoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PedidoId      int64                  `protobuf:"varint,1,opt,name=pedido_id,json=pedidoId,proto3" json:"pedido_id,omitempty"`
	Valor         float64                `protobuf:"fixed64,2,opt,name=valor,proto3" json:"valor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessarPagamentoRequest) Reset() {
	*x = ProcessarPagamentoRequest{}
	mi := &file_proto_pagamentos_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessarPagamentoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessarPagamentoRequest) ProtoMessage() {}

func (x *ProcessarPagamentoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pagamentos_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessarPagamentoRequest.ProtoReflect.Descriptor instead.
func (*ProcessarPagamentoRequest) Descriptor() ([]byte, []int) {
	return file_proto_pagamentos_proto_rawDescGZIP(), []int{0}
}

func (x *ProcessarPagamentoRequest) GetPedidoId() int64 {
	if x != nil {
		return x.PedidoId
	}
	return 0
}

func (x *ProcessarPagamentoRequest) GetValor() float64 {
	if x != nil {
		return x.Valor
	}
	return 0
}

type ProcessarPagamentoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessarPagamentoResponse) Reset() {
	*x = ProcessarPagamentoResponse{}
	mi := &file_proto_pagamentos_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessarPagamentoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessarPagamentoResponse) ProtoMessage() {}

func (x *ProcessarPagamentoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pagamentos_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessarPagamentoResponse.ProtoReflect.Descriptor instead.
func (*ProcessarPagamentoResponse) Descriptor() ([]byte, []int) {
	return file_proto_pagamentos_proto_rawDescGZIP(), []int{1}
}

func (x *ProcessarPagamentoResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_proto_pagamentos_proto protoreflect.FileDescriptor

const file_proto_pagamentos_proto_rawDesc = "" +
	"\n" +
	"\x16proto/pagamentos.proto\x12\n" +
	"pagamentos\"N\n" +
	"\x19ProcessarPagamentoRequest\x12\x1b\n" +
	"\tpedido_id\x18\x01 \x01(\x03R\bpedidoId\x12\x14\n" +
	"\x05valor\x18\x02 \x01(\x01R\x05valor\"4\n" +
	"\x1aProcessarPagamentoResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status2x\n" +
	"\x11PagamentosService\x12c\n" +
	"\x12ProcessarPagamento\x12%.pagamentos.ProcessarPagamentoRequest\x1a&.pagamentos.ProcessarPagamentoResponseB!Z\x1fecommerce-grpc/proto/pagamentosb\x06proto3"

var (
	file_proto_pagamentos_proto_rawDescOnce sync.Once
	file_proto_pagamentos_proto_rawDescData []byte
)

func file_proto_pagamentos_proto_rawDescGZIP() []byte {
	file_proto_pagamentos_proto_rawDescOnce.Do(func() {
		file_proto_pagamentos_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_pagamentos_proto_rawDesc), len(file_proto_pagamentos_proto_rawDesc)))
	})
	return file_proto_pagamentos_proto_rawDescData
}

var file_proto_pagamentos_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_pagamentos_proto_goTypes = []any{
	(*ProcessarPagamentoRequest)(nil),  // 0: pagamentos.ProcessarPagamentoRequest
	(*ProcessarPagamentoResponse)(nil), // 1: pagamentos.ProcessarPagamentoResponse
}
var file_proto_pagamentos_proto_depIdxs = []int32{
	0, // 0: pagamentos.PagamentosService.ProcessarPagamento:input_type -> pagamentos.ProcessarPagamentoRequest
	1, // 1: pagamentos.PagamentosService.ProcessarPagamento:output_type -> pagamentos.ProcessarPagamentoResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_pagamentos_proto_init() }
func file_proto_pagamentos_proto_init() {
	if File_proto_pagamentos_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_pagamentos_proto_rawDesc), len(file_proto_pagamentos_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_pagamentos_proto_goTypes,
		DependencyIndexes: file_proto_pagamentos_proto_depIdxs,
		MessageInfos:      file_proto_pagamentos_proto_msgTypes,
	}.Build()
	File_proto_pagamentos_proto = out.File
	file_proto_pagamentos_proto_goTypes = nil
	file_proto_pagamentos_proto_depIdxs = nil
}
