// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.31.1
// source: proto/pagamentos.proto

package pagamentos

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PagamentosService_ProcessarPagamento_FullMethodName = "/pagamentos.PagamentosService/ProcessarPagamento"
)

// PagamentosServiceClient is the client API for PagamentosService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PagamentosServiceClient interface {
	ProcessarPagamento(ctx context.Context, in *ProcessarPagamentoRequest, opts ...grpc.CallOption) (*ProcessarPagamentoResponse, error)
}

type pagamentosServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPagamentosServiceClient(cc grpc.ClientConnInterface) PagamentosServiceClient {
	return &pagamentosServiceClient{cc}
}

func (c *pagamentosServiceClient) ProcessarPagamento(ctx context.Context, in *ProcessarPagamentoRequest, opts ...grpc.CallOption) (*ProcessarPagamentoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProcessarPagamentoResponse)
	err := c.cc.Invoke(ctx, PagamentosService_ProcessarPagamento_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PagamentosServiceServer is the server API for PagamentosService service.
// All implementations must embed UnimplementedPagamentosServiceServer
// for forward compatibility.
type PagamentosServiceServer interface {
	ProcessarPagamento(context.Context, *ProcessarPagamentoRequest) (*ProcessarPagamentoResponse, error)
	mustEmbedUnimplementedPagamentosServiceServer()
}

// UnimplementedPagamentosServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPagamentosServiceServer struct{}

func (UnimplementedPagamentosServiceServer) ProcessarPagamento(context.Context, *ProcessarPagamentoRequest) (*ProcessarPagamentoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ProcessarPagamento not implemented")
}
func (UnimplementedPagamentosServiceServer) mustEmbedUnimplementedPagamentosServiceServer() {}
func (UnimplementedPagamentosServiceServer) testEmbeddedByValue()                           {}

// UnsafePagamentosServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PagamentosServiceServer will
// result in compilation errors.
type UnsafePagamentosServiceServer interface {
	mustEmbedUnimplementedPagamentosServiceServer()
}

func RegisterPagamentosServiceServer(s grpc.ServiceRegistrar, srv PagamentosServiceServer) {
	// If the following call pancis, it indicates UnimplementedPagamentosServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PagamentosService_ServiceDesc, srv)
}

func _PagamentosService_ProcessarPagamento_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProcessarPagamentoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PagamentosServiceServer).ProcessarPagamento(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PagamentosService_ProcessarPagamento_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PagamentosServiceServer).ProcessarPagamento(ctx, req.(*ProcessarPagamentoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PagamentosService_ServiceDesc is the grpc.ServiceDesc for PagamentosService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PagamentosService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pagamentos.PagamentosService",
	HandlerType: (*PagamentosServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ProcessarPagamento",
			Handler:    _PagamentosService_ProcessarPagamento_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/pagamentos.proto",
}
